{{ if .Values.ltc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: litecoind
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: jsonrpc
    port: 9332
    protocol: TCP
    targetPort: 9332
  - name: nginx
    port: 5555
    protocol: TCP
    targetPort: 80
  selector:
    app: litecoind
{{ end }}