{{ if .Values.polygon_fullnode.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: polygon
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: polygon
  ports:
  - name: erigon-port-tcp
    port: 30303
    protocol: TCP
  - name: erigon-port-udp
    port: 30303
    protocol: UDP
  - name: erigon-rpc
    port: 8545
    protocol: TCP
{{ end }}
