{{- if .Values.polygon_fullnode.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polygon
  namespace: {{ .Values.namespace }}
  labels:
    app: polygon
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: polygon
  template:
    metadata:
      labels:
        app: polygon
    spec:
      terminationGracePeriodSeconds: 300
      tolerations: {{- toYaml .Values.polygon_fullnode.tolerations | nindent 8 }}
      nodeSelector: {{- toYaml .Values.polygon_fullnode.nodeSelector | nindent 8 }}
      containers:

        - name: erigon
          image: 0xpolygon/erigon:v3.7.2 #erigontech/erigon:v3.5.0
          args:
            {{- if .Values.polygon_fullnode.mainnet }}
            - --chain=bor-mainnet
            {{- else }}
            - --chain=amoy
            {{- end }}
            - --bor.heimdall=https://heimdall-api.polygon.technology
            - --http.addr=0.0.0.0
            - --http.api=eth,web3,net,debug,trace,txpool
            - --torrent.download.rate=512mb
            - --prune.mode=minimal
            - --http.vhosts=*

          volumeMounts:
            - name: erigon-volume
              mountPath: /home/erigon/

      volumes:
        - name: erigon-volume
          persistentVolumeClaim:
            claimName: erigon-volume

{{- end }}

